### ISSUE TITLE
ValueError: Unable to find DS1307 at i2c address 0x68.

### ISSUE THREAD

**Issue by soneups** [adafruit/Adafruit_CircuitPython_DS1307#10]
if i 'i2c.scan()' i can see the ds1307 at 0x68 however the last command to setup the rtc fails with an unable to find DS1307 at i2c address ox68 - any help or points greatly appreciated!

Adafruit CircuitPython 3.1.2 on 2019-01-07; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import busio
>>> import adafruit_ds1307
>>> import time
>>> from board import *
>>> myI2C = busio.I2C(SCL, SDA)
>>> rtc = adafruit_ds1307.DS1307(myI2C)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ds1307.py", line 85, in __init__
ValueError: Unable to find DS1307 at i2c address 0x68.

**Comment by soneups** [comment]
Self resolving.

**Comment by Snudi** [comment]
@soneups : How did you solve it? im getting the same error with my RP2040 Board (Pimoroni Plasma Board) and a Sparkfun DS1307 Module. The Device Address is fine (0x68) and the SDA/SCL Pulled up but with the Adafruit DS1307 Library im getting the "ValueError: Unable to find DS1307 at i2c address 0x68." Error
Thanks a lot, Ruediger

**Comment by Snudi** [comment]
I solved it by Myself. In the Original .py File was a section to verify the correct RTC Board. 
`# Try and verify this is the RTC we expect by checking the rate select
        # control bits which are 1 on reset and shouldn't ever be changed.
        buf = bytearray(2)
        buf[0] = 0x07
        with self.i2c_device as i2c:
            i2c.write_then_readinto(buf, buf, out_end=1, in_start=1)

        if (buf[1] & 0b00000011) != 0b00000011:
            raise ValueError("Unable to find DS1307 at i2c address 0x68.")`

I removed it completly because i know it is the right board. Then i created a new DS1307 Library without this code. I append it on my comment. Now it works fine. Hope i could help someone with it in the Future. Best Ruediger


[adafruit_ds1307.zip](https://github.com/adafruit/Adafruit_CircuitPython_DS1307/files/7651539/adafruit_ds1307.zip)
.

**Comment by coplate** [comment]
I have submitted a Pull request for this issue, as the existing validation mentioned does not reflect the manufacturers documentation.  Those 2 bits are intended to be alterable, not fixed.
https://github.com/adafruit/Adafruit_CircuitPython_DS1307/pull/24
